
;   Riccardo Cafagna 
;
;   3 first PORTB ligths -> green
;   2 middle PORTB lights -> yellow
;   3 last PORTB lights -> red
;   Uses timer interrupt to count
;
    
    #include "p16f877a.inc"
 __CONFIG _FOSC_EXTRC & _WDTE_OFF & _PWRTE_OFF & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF
 
 GPR_VAR    UDATA
 COUNT8	    RES	    1
	   
VERDE EQU B'00000111'	    
AMARELO EQU B'00011000'
VERMELHO EQU B'11100000'
	    
 BANK0 MACRO
 BCF STATUS, RP1;RP1:RP0
 BCF STATUS, RP0
 ENDM

 BANK1 MACRO
 BCF STATUS, RP1;RP1:RP0
 BSF STATUS, RP0
 ENDM

 BANK2 MACRO
 BSF STATUS, RP1;RP1:RP0
 BCF STATUS, RP0
 ENDM

 BANK3 MACRO
 BSF STATUS, RP1;RP1:RP0
 BSF STATUS, RP0
 ENDM
    
RES_VECT  CODE    0x0000            
    GOTO    START                   

ISR CODE 0X0004
 BTFSC INTCON, TMR0IF
 CALL TMR0_INT
RETFIE
 
TMR0_INT
   BCF INTCON, TMR0IF
   MOVLW D'12'
   MOVF TMR0
   
   DECFSZ COUNT8
   RETURN
   
   MOVLW D'8'
   MOVWF COUNT8
   
   MOVF PORTD, W
   XORLW VERDE
   BTFSC STATUS, Z
   GOTO VERDE_STATE
   
   MOVF PORTD, W
   XORLW AMARELO
   BTFSC STATUS,Z
   GOTO AMARELO_STATE
   
    MOVF PORTD, W
   XORLW VERMELHO
   BTFSC STATUS,Z
   GOTO VERMELHO_STATE
   
VERDE_STATE
     MOVLW AMARELO
     MOVWF PORTD

     MOVLW D'8'
     MOVWF COUNT8
     RETURN
AMARELO_STATE
     MOVLW VERMELHO
     MOVWF PORTD
     MOVLW D'16'
     MOVWF COUNT8
     RETURN
VERMELHO_STATE
     MOVLW VERDE
     MOVWF PORTD
     MOVLW D'24'
     MOVWF COUNT8
     RETURN
	
MAIN_PROG CODE                      

START
 
 BANK1
 CLRF TRISD
 
 BCF OPTION_REG, PSA; HABILITA PSA PRO TIMER 0
 BSF OPTION_REG, PS2
 BSF OPTION_REG, PS1
 BCF OPTION_REG, PS0
 BANK0
 BCF TRISB, RB1
 
 MOVLW D'12'
 MOVWF TMR0
 
 MOVLW D'8'
 MOVWF COUNT8

 MOVLW VERDE
 MOVWF PORTD
 
 BCF INTCON, TMR0IF
 BSF INTCON, TMR0IE
 BSF INTCON, GIE
 
    GOTO $                          

    END